site_name: MC^2 Documentation
pages:
  - Index: 'index.md'
  - UI Library:
    - Overview: 'ui-library/overview.md'

  - Alert Library:
      - Overview: 'alert-library/overview.md'

  - Message Format: 'message-format.md'

  - Classes:
    - UI.BasicControl: 'ui-library/controls/basic-control.md'
    - Alert.Alert: 'alert-library/dialogs/alert.md'
    - Alert.Notification: 'alert-library/overlays/notification.md'
theme:
  name: 'material'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - toc:
      permalink: true